notification-services:
  telegram: true
  email: false

bot:
  config:
    message-sender-sleep-time: 1000
  telegram:
    token: "1837475911:AAGs4Fl6je0G83xscIXMPXyd_DxeR4GDkyA"
    name: "notification_yalta_bot"
    consumers:
      - "207181187" #sasha_yalta

email:
  config:
    host: "smtp.gmail.com"
    port: 587
    username: "notification.yalta@gmail.com"
    password: "rootroot123"
    connectionTimeout: "1"
    addressees:
      - "sidailen.me@gmail.com"

spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yalta
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect